resources:
- name: hellosnake
  type: git
  source:
    uri: https://github.com/y238wang/hellosnake
- name: cf-production
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

jobs:
- name: deploy
  plan:
    - get: hellosnake
      trigger: true
    - task: deploy_task
      config:
        platform: linux
        inputs:
        - name: hellosnake
        outputs:
        - name: build-output
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: '7.9.0-alpine'
        run:
          path: sh
          args:
          - -exc
          - |
            mv hellosnake/* build-output
    - put: cf-production
      params:
        manifest: build-output/manifest.yml
        path: build-output
