resources:
- name: hellosnake
  type: git
  source:
    uri: https://github.com/y238wang/hellosnake

jobs:
- name: deploy
  plan:
    - get: hellosnake
    - task: deploy_task
      config:
        platform: linux
        inputs:
        - name: hellosnake
        image_resource:
          type: docker-image
          source: { repository: ubuntu }
        run:
          path: echo
          args:
          - "Hello Snake"

