jobs:
- name: hello_snake_job
  plan:
    - task: hello_snake_task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: { repository: ubuntu }
        run:
          path: echo
          args:
          - "Hello Snake"

